/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sdfs.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
sdfs_prog_0x0001(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		READ_REQ_T rpc_read_0x0001_arg;
		WRITE_REQ_T rpc_write_0x0001_arg;
		OPEN_REQ_T rpc_open_0x0001_arg;
		CREATE_REQ_T rpc_create_0x0001_arg;
		GETATTR_REQ_T rpc_getattr_0x0001_arg;
		READDIR_REQ_T rpc_readdir_0x0001_arg;
		ACCESS_REQ_T rpc_access_0x0001_arg;
		MKNOD_REQ_T rpc_mknod_0x0001_arg;
		MKDIR_REQ_T rpc_mkdir_0x0001_arg;
		char *rpc_unlink_0x0001_arg;
		char *rpc_rmdir_0x0001_arg;
		SYMLINK_REQ_T rpc_symlink_0x0001_arg;
		RENAME_REQ_T rpc_rename_0x0001_arg;
		LINK_REQ_T rpc_link_0x0001_arg;
		CHMOD_REQ_T rpc_chmod_0x0001_arg;
		CHOWN_REQ_T rpc_chown_0x0001_arg;
		TRUNCATE_REQ_T rpc_truncate_0x0001_arg;
		READLINK_REQ_T rpc_readlink_0x0001_arg;
		char *rpc_statvfs_0x0001_arg;
		SETXATTR_REQ_T rpc_setxattr_0x0001_arg;
		GETXATTR_REQ_T rpc_getxattr_0x0001_arg;
		LISTXATTR_REQ_T rpc_listxattr_0x0001_arg;
		REMOVEXATTR_REQ_T rpc_removexattr_0x0001_arg;
		FALLOCATE_REQ_T rpc_fallocate_0x0001_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case rpc_read:
		_xdr_argument = (xdrproc_t) xdr_READ_REQ_T;
		_xdr_result = (xdrproc_t) xdr_READ_RSP_T;
		local = (char *(*)(char *, struct svc_req *)) rpc_read_0x0001_svc;
		break;

	case rpc_write:
		_xdr_argument = (xdrproc_t) xdr_WRITE_REQ_T;
		_xdr_result = (xdrproc_t) xdr_WRITE_RSP_T;
		local = (char *(*)(char *, struct svc_req *)) rpc_write_0x0001_svc;
		break;

	case rpc_open:
		_xdr_argument = (xdrproc_t) xdr_OPEN_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_open_0x0001_svc;
		break;

	case rpc_create:
		_xdr_argument = (xdrproc_t) xdr_CREATE_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_create_0x0001_svc;
		break;

	case rpc_getattr:
		_xdr_argument = (xdrproc_t) xdr_GETATTR_REQ_T;
		_xdr_result = (xdrproc_t) xdr_GETATTR_RSP_T;
		local = (char *(*)(char *, struct svc_req *)) rpc_getattr_0x0001_svc;
		break;

	case rpc_readdir:
		_xdr_argument = (xdrproc_t) xdr_READDIR_REQ_T;
		_xdr_result = (xdrproc_t) xdr_READDIR_RSP_T;
		local = (char *(*)(char *, struct svc_req *)) rpc_readdir_0x0001_svc;
		break;

	case rpc_access:
		_xdr_argument = (xdrproc_t) xdr_ACCESS_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_access_0x0001_svc;
		break;

	case rpc_mknod:
		_xdr_argument = (xdrproc_t) xdr_MKNOD_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_mknod_0x0001_svc;
		break;

	case rpc_mkdir:
		_xdr_argument = (xdrproc_t) xdr_MKDIR_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_mkdir_0x0001_svc;
		break;

	case rpc_unlink:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_unlink_0x0001_svc;
		break;

	case rpc_rmdir:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_rmdir_0x0001_svc;
		break;

	case rpc_symlink:
		_xdr_argument = (xdrproc_t) xdr_SYMLINK_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_symlink_0x0001_svc;
		break;

	case rpc_rename:
		_xdr_argument = (xdrproc_t) xdr_RENAME_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_rename_0x0001_svc;
		break;

	case rpc_link:
		_xdr_argument = (xdrproc_t) xdr_LINK_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_link_0x0001_svc;
		break;

	case rpc_chmod:
		_xdr_argument = (xdrproc_t) xdr_CHMOD_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_chmod_0x0001_svc;
		break;

	case rpc_chown:
		_xdr_argument = (xdrproc_t) xdr_CHOWN_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_chown_0x0001_svc;
		break;

	case rpc_truncate:
		_xdr_argument = (xdrproc_t) xdr_TRUNCATE_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_truncate_0x0001_svc;
		break;

	case rpc_readlink:
		_xdr_argument = (xdrproc_t) xdr_READLINK_REQ_T;
		_xdr_result = (xdrproc_t) xdr_READLINK_RSP_T;
		local = (char *(*)(char *, struct svc_req *)) rpc_readlink_0x0001_svc;
		break;

	case rpc_statvfs:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_STATVFS_RSP_T;
		local = (char *(*)(char *, struct svc_req *)) rpc_statvfs_0x0001_svc;
		break;

	case rpc_setxattr:
		_xdr_argument = (xdrproc_t) xdr_SETXATTR_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_setxattr_0x0001_svc;
		break;

	case rpc_getxattr:
		_xdr_argument = (xdrproc_t) xdr_GETXATTR_REQ_T;
		_xdr_result = (xdrproc_t) xdr_GETXATTR_RSP_T;
		local = (char *(*)(char *, struct svc_req *)) rpc_getxattr_0x0001_svc;
		break;

	case rpc_listxattr:
		_xdr_argument = (xdrproc_t) xdr_LISTXATTR_REQ_T;
		_xdr_result = (xdrproc_t) xdr_LISTXATTR_RSP_T;
		local = (char *(*)(char *, struct svc_req *)) rpc_listxattr_0x0001_svc;
		break;

	case rpc_removexattr:
		_xdr_argument = (xdrproc_t) xdr_REMOVEXATTR_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_removexattr_0x0001_svc;
		break;

	case rpc_fallocate:
		_xdr_argument = (xdrproc_t) xdr_FALLOCATE_REQ_T;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fallocate_0x0001_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

extern void parse_cmd(int,char **);

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	parse_cmd(argc,argv);

	pmap_unset (SDFS_PROG, SDFS_V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SDFS_PROG, SDFS_V1, sdfs_prog_0x0001, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SDFS_PROG, SDFS_V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SDFS_PROG, SDFS_V1, sdfs_prog_0x0001, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SDFS_PROG, SDFS_V1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
