/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sdfs.h"

bool_t
xdr_read_req (XDR *xdrs, read_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_READ_REQ_T (XDR *xdrs, READ_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_read_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_rsp (XDR *xdrs, read_rsp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_READ_RSP_T (XDR *xdrs, READ_RSP_T *objp)
{
	register int32_t *buf;

	 if (!xdr_read_rsp (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_req (XDR *xdrs, write_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_WRITE_REQ_T (XDR *xdrs, WRITE_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_write_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_rsp (XDR *xdrs, write_rsp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_WRITE_RSP_T (XDR *xdrs, WRITE_RSP_T *objp)
{
	register int32_t *buf;

	 if (!xdr_write_rsp (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getattr_req (XDR *xdrs, getattr_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GETATTR_REQ_T (XDR *xdrs, GETATTR_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_getattr_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getattr_rsp (XDR *xdrs, getattr_rsp *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->err))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->ino))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->mode))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->uid))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->gid))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->atime))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->mtime))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->ctime))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->nlink))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->size))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->err);
			IXDR_PUT_U_LONG(buf, objp->ino);
			IXDR_PUT_U_LONG(buf, objp->mode);
			IXDR_PUT_U_LONG(buf, objp->uid);
			IXDR_PUT_U_LONG(buf, objp->gid);
			IXDR_PUT_U_LONG(buf, objp->atime);
			IXDR_PUT_U_LONG(buf, objp->mtime);
			IXDR_PUT_U_LONG(buf, objp->ctime);
			IXDR_PUT_U_LONG(buf, objp->nlink);
			IXDR_PUT_U_LONG(buf, objp->size);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->err))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->ino))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->mode))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->uid))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->gid))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->atime))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->mtime))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->ctime))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->nlink))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->size))
				 return FALSE;
		} else {
			objp->err = IXDR_GET_LONG(buf);
			objp->ino = IXDR_GET_U_LONG(buf);
			objp->mode = IXDR_GET_U_LONG(buf);
			objp->uid = IXDR_GET_U_LONG(buf);
			objp->gid = IXDR_GET_U_LONG(buf);
			objp->atime = IXDR_GET_U_LONG(buf);
			objp->mtime = IXDR_GET_U_LONG(buf);
			objp->ctime = IXDR_GET_U_LONG(buf);
			objp->nlink = IXDR_GET_U_LONG(buf);
			objp->size = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->ino))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->uid))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->gid))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->atime))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mtime))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->ctime))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->nlink))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GETATTR_RSP_T (XDR *xdrs, GETATTR_RSP_T *objp)
{
	register int32_t *buf;

	 if (!xdr_getattr_rsp (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readdir_req (XDR *xdrs, readdir_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_READDIR_REQ_T (XDR *xdrs, READDIR_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_readdir_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readdir_rsp (XDR *xdrs, readdir_rsp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_READDIR_RSP_T (XDR *xdrs, READDIR_RSP_T *objp)
{
	register int32_t *buf;

	 if (!xdr_readdir_rsp (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_open_req (XDR *xdrs, open_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->flag))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OPEN_REQ_T (XDR *xdrs, OPEN_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_open_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_req (XDR *xdrs, access_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mask))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ACCESS_REQ_T (XDR *xdrs, ACCESS_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_access_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readlink_req (XDR *xdrs, readlink_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_READLINK_REQ_T (XDR *xdrs, READLINK_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_readlink_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readlink_rsp (XDR *xdrs, readlink_rsp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_READLINK_RSP_T (XDR *xdrs, READLINK_RSP_T *objp)
{
	register int32_t *buf;

	 if (!xdr_readlink_rsp (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mknod_req (XDR *xdrs, mknod_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dev))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MKNOD_REQ_T (XDR *xdrs, MKNOD_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_mknod_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mkdir_req (XDR *xdrs, mkdir_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MKDIR_REQ_T (XDR *xdrs, MKDIR_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_mkdir_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_symlink_req (XDR *xdrs, symlink_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->from, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->to, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SYMLINK_REQ_T (XDR *xdrs, SYMLINK_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_symlink_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rename_req (XDR *xdrs, rename_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->from, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->to, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RENAME_REQ_T (XDR *xdrs, RENAME_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_rename_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_link_req (XDR *xdrs, link_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->from, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->to, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LINK_REQ_T (XDR *xdrs, LINK_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_link_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_chmod_req (XDR *xdrs, chmod_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CHMOD_REQ_T (XDR *xdrs, CHMOD_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_chmod_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_chown_req (XDR *xdrs, chown_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->uid))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->gid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CHOWN_REQ_T (XDR *xdrs, CHOWN_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_chown_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_truncate_req (XDR *xdrs, truncate_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TRUNCATE_REQ_T (XDR *xdrs, TRUNCATE_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_truncate_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_statvfs_rsp (XDR *xdrs, statvfs_rsp *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (12 +  6 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->err))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->bsize))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->frsize))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->blocks))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->bfree))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->bavail))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->files))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->ffree))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->favail))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->fsid))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->flag))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->namemax))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->spare, 6,
				sizeof (u_int), (xdrproc_t) xdr_u_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->err);
			IXDR_PUT_U_LONG(buf, objp->bsize);
			IXDR_PUT_U_LONG(buf, objp->frsize);
			IXDR_PUT_U_LONG(buf, objp->blocks);
			IXDR_PUT_U_LONG(buf, objp->bfree);
			IXDR_PUT_U_LONG(buf, objp->bavail);
			IXDR_PUT_U_LONG(buf, objp->files);
			IXDR_PUT_U_LONG(buf, objp->ffree);
			IXDR_PUT_U_LONG(buf, objp->favail);
			IXDR_PUT_U_LONG(buf, objp->fsid);
			IXDR_PUT_U_LONG(buf, objp->flag);
			IXDR_PUT_U_LONG(buf, objp->namemax);
			{
				register u_int *genp;

				for (i = 0, genp = objp->spare;
					i < 6; ++i) {
					IXDR_PUT_U_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (12 +  6 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->err))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->bsize))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->frsize))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->blocks))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->bfree))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->bavail))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->files))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->ffree))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->favail))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->fsid))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->flag))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->namemax))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->spare, 6,
				sizeof (u_int), (xdrproc_t) xdr_u_int))
				 return FALSE;
		} else {
			objp->err = IXDR_GET_LONG(buf);
			objp->bsize = IXDR_GET_U_LONG(buf);
			objp->frsize = IXDR_GET_U_LONG(buf);
			objp->blocks = IXDR_GET_U_LONG(buf);
			objp->bfree = IXDR_GET_U_LONG(buf);
			objp->bavail = IXDR_GET_U_LONG(buf);
			objp->files = IXDR_GET_U_LONG(buf);
			objp->ffree = IXDR_GET_U_LONG(buf);
			objp->favail = IXDR_GET_U_LONG(buf);
			objp->fsid = IXDR_GET_U_LONG(buf);
			objp->flag = IXDR_GET_U_LONG(buf);
			objp->namemax = IXDR_GET_U_LONG(buf);
			{
				register u_int *genp;

				for (i = 0, genp = objp->spare;
					i < 6; ++i) {
					*genp++ = IXDR_GET_U_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->bsize))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->frsize))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->blocks))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->bfree))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->bavail))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->files))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->ffree))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->favail))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->fsid))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->flag))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->namemax))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->spare, 6,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_STATVFS_RSP_T (XDR *xdrs, STATVFS_RSP_T *objp)
{
	register int32_t *buf;

	 if (!xdr_statvfs_rsp (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_create_req (XDR *xdrs, create_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flag))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CREATE_REQ_T (XDR *xdrs, CREATE_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_create_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_setxattr_req (XDR *xdrs, setxattr_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, 256))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->value.value_val, (u_int *) &objp->value.value_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flag))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SETXATTR_REQ_T (XDR *xdrs, SETXATTR_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_setxattr_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getxattr_req (XDR *xdrs, getxattr_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, 256))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GETXATTR_REQ_T (XDR *xdrs, GETXATTR_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_getxattr_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getxattr_rsp (XDR *xdrs, getxattr_rsp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->value.value_val, (u_int *) &objp->value.value_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GETXATTR_RSP_T (XDR *xdrs, GETXATTR_RSP_T *objp)
{
	register int32_t *buf;

	 if (!xdr_getxattr_rsp (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listxattr_req (XDR *xdrs, listxattr_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LISTXATTR_REQ_T (XDR *xdrs, LISTXATTR_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_listxattr_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listxattr_rsp (XDR *xdrs, listxattr_rsp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->value.value_val, (u_int *) &objp->value.value_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LISTXATTR_RSP_T (XDR *xdrs, LISTXATTR_RSP_T *objp)
{
	register int32_t *buf;

	 if (!xdr_listxattr_rsp (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_removexattr_req (XDR *xdrs, removexattr_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_REMOVEXATTR_REQ_T (XDR *xdrs, REMOVEXATTR_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_removexattr_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fallocate_req (XDR *xdrs, fallocate_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, 256))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FALLOCATE_REQ_T (XDR *xdrs, FALLOCATE_REQ_T *objp)
{
	register int32_t *buf;

	 if (!xdr_fallocate_req (xdrs, objp))
		 return FALSE;
	return TRUE;
}
